binocular:
  arangodb:
    migration:
      default-user-email-template: "{name}@users.noreply.binocular.inso-world.com"
      default-project-name: Binocular
    database:
      name: "binocular-repo"
      host: "localhost"
      port: 8529
      user: TODO
      password: TODO
