import { DashboardLayoutCategory, type DashboardLayout } from '../../../types/general/dashboardLayoutType';

const dashboard: DashboardLayout = {
  category: DashboardLayoutCategory.DEBUG,
  name: 'All Visualizations',
  items: [
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Repository Stats',
      dataPluginId: undefined,
      x: 0,
      y: 0,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Changes',
      dataPluginId: undefined,
      x: 10,
      y: 0,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Builds',
      dataPluginId: undefined,
      x: 20,
      y: 0,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Issues',
      dataPluginId: undefined,
      x: 30,
      y: 0,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Merge Requests',
      dataPluginId: undefined,
      x: 0,
      y: 10,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Time Spent',
      dataPluginId: undefined,
      x: 10,
      y: 10,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Sum Commits',
      dataPluginId: undefined,
      x: 20,
      y: 10,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Code Ownership',
      dataPluginId: undefined,
      x: 30,
      y: 10,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Collaboration',
      dataPluginId: undefined,
      x: 0,
      y: 20,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Knowledge Radar',
      dataPluginId: undefined,
      x: 10,
      y: 20,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Code Expertise',
      dataPluginId: undefined,
      x: 20,
      y: 20,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Repository Activity',
      dataPluginId: undefined,
      x: 30,
      y: 20,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Burndown',
      dataPluginId: undefined,
      x: 0,
      y: 30,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Issues Timeline',
      dataPluginId: undefined,
      x: 10,
      y: 30,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Code Hotspots',
      dataPluginId: undefined,
      x: 20,
      y: 30,
      settings: undefined,
    },
    {
      id: 0,
      width: 10,
      height: 10,
      pluginName: 'Change Frequency',
      dataPluginId: undefined,
      x: 30,
      y: 30,
      settings: undefined,
    },
  ],
};

export default dashboard;
