import { DashboardLayoutCategory, type DashboardLayout } from '../../../types/general/dashboardLayoutType';

const dashboard: DashboardLayout = {
  category: DashboardLayoutCategory.ADVANCED,
  name: 'Delivery Health',
  items: [
    {
      id: 0,
      width: 10,
      height: 12,
      pluginName: 'Repository Stats',
      dataPluginId: undefined,
      x: 0,
      y: 0,
      settings: { commits: true, contributors: false, issues: true, builds: true, mergeRequests: true },
    },
    {
      id: 0,
      width: 30,
      height: 12,
      pluginName: 'Builds',
      dataPluginId: undefined,
      x: 10,
      y: 0,
      settings: { splitBuildsPerAuthor: true, visualizationStyle: 'linear', showSprints: true },
    },
    {
      id: 0,
      width: 20,
      height: 12,
      pluginName: 'Burndown',
      dataPluginId: undefined,
      x: 0,
      y: 12,
      settings: { showSprints: true },
    },
    {
      id: 0,
      width: 20,
      height: 12,
      pluginName: 'Time Spent',
      dataPluginId: undefined,
      x: 20,
      y: 12,
      settings: {
        splitTimePerIssue: true,
        splitSpentRemoved: true,
        breakdown: false,
        visualizationStyle: 'curved',
        showSprints: false,
      },
    },
    {
      id: 0,
      width: 20,
      height: 16,
      pluginName: 'Sum Commits',
      dataPluginId: undefined,
      x: 0,
      y: 24,
      settings: { showMean: true, showOther: false, minCommits: 0, topN: 15, visualizationStyle: 'curved', showSprints: false },
    },
    {
      id: 0,
      width: 20,
      height: 16,
      pluginName: 'Repository Activity',
      dataPluginId: undefined,
      x: 20,
      y: 24,
      settings: undefined,
    },
  ],
};

export default dashboard;
