import { DashboardLayoutCategory, type DashboardLayout } from '../../../types/general/dashboardLayoutType';

const dashboard: DashboardLayout = {
  category: DashboardLayoutCategory.BASIC,
  name: 'Issue',
  items: [
    {
      id: 0,
      width: 40,
      height: 8,
      pluginName: 'Issues',
      dataPluginId: undefined,
      x: 0,
      y: 0,
      settings: { splitIssuesPerAuthor: true, breakdown: true, visualizationStyle: 'curved', showSprints: true },
    },
    {
      id: 0,
      width: 10,
      height: 12,
      pluginName: 'Repository Stats',
      dataPluginId: undefined,
      x: 0,
      y: 8,
      settings: { commits: false, contributors: true, issues: true, builds: false, mergeRequests: true },
    },
    {
      id: 0,
      width: 30,
      height: 12,
      pluginName: 'Collaboration',
      dataPluginId: undefined,
      x: 10,
      y: 8,
      settings: { minEdgeValue: 2, maxEdgeValue: 80, includeCommitMessageRefs: true, visualizationStyle: 'curved', showSprints: false },
    },
    {
      id: 0,
      width: 40,
      height: 8,
      pluginName: 'Merge Requests',
      dataPluginId: undefined,
      x: 0,
      y: 20,
      settings: { splitMergeRequestsPerAuthor: true, breakdown: true, visualizationStyle: 'curved', showSprints: false },
    },
    {
      id: 0,
      width: 20,
      height: 12,
      pluginName: 'Issues Timeline',
      dataPluginId: undefined,
      x: 0,
      y: 28,
      settings: {
        showSprints: true,
        coloringMode: 'time-spent',
        maxNumberOfDifferencesBetweenLabels: 4,
        minNumberOfLabelsPerGroup: 2,
      },
    },
    {
      id: 0,
      width: 20,
      height: 12,
      pluginName: 'Burndown',
      dataPluginId: undefined,
      x: 20,
      y: 28,
      settings: { showSprints: true },
    },
  ],
};

export default dashboard;
