import { DashboardLayoutCategory, type DashboardLayout } from '../../../types/general/dashboardLayoutType';

const dashboard: DashboardLayout = {
  category: DashboardLayoutCategory.BASIC,
  name: 'Ownership',
  items: [
    {
      id: 0,
      width: 40,
      height: 8,
      pluginName: 'Code Ownership',
      dataPluginId: undefined,
      x: 0,
      y: 0,
      settings: {
        displayMode: 'relative',
        currentBranch: undefined,
        visualizationStyle: 'curved',
        showSprints: false,
      },
    },
    {
      id: 0,
      width: 20,
      height: 8,
      pluginName: 'Builds',
      dataPluginId: undefined,
      x: 0,
      y: 8,
      settings: { splitBuildsPerAuthor: true, visualizationStyle: 'stepped', showSprints: false },
    },
    {
      id: 0,
      width: 20,
      height: 8,
      pluginName: 'Changes',
      dataPluginId: undefined,
      x: 20,
      y: 8,
      settings: { splitAdditionsDeletions: false, visualizationStyle: 'curved', showSprints: false },
    },
    {
      id: 0,
      width: 16,
      height: 24,
      pluginName: 'Code Expertise',
      dataPluginId: undefined,
      x: 0,
      y: 16,
      settings: undefined,
    },
    {
      id: 0,
      width: 12,
      height: 24,
      pluginName: 'Knowledge Radar',
      dataPluginId: undefined,
      x: 16,
      y: 16,
      settings: undefined,
    },
    {
      id: 0,
      width: 12,
      height: 24,
      pluginName: 'Collaboration',
      dataPluginId: undefined,
      x: 28,
      y: 16,
      settings: { minEdgeValue: 2, maxEdgeValue: 60, includeCommitMessageRefs: true },
    },
  ],
};

export default dashboard;
