import { DashboardLayoutCategory, type DashboardLayout } from '../../../types/general/dashboardLayoutType';

const dashboard: DashboardLayout = {
  category: DashboardLayoutCategory.BASIC,
  name: 'Sprint Health',
  items: [
    {
      id: 0,
      width: 20,
      height: 12,
      pluginName: 'Burndown',
      dataPluginId: undefined,
      x: 0,
      y: 0,
      settings: undefined,
    },
    {
      id: 0,
      width: 20,
      height: 12,
      pluginName: 'Issues Timeline',
      dataPluginId: undefined,
      x: 20,
      y: 0,
      settings: undefined,
    },
    {
      id: 0,
      width: 20,
      height: 12,
      pluginName: 'Collaboration',
      dataPluginId: undefined,
      x: 0,
      y: 12,
      settings: undefined,
    },
    {
      id: 0,
      width: 20,
      height: 12,
      pluginName: 'Sum Commits',
      dataPluginId: undefined,
      x: 20,
      y: 12,
      settings: undefined,
    },
    {
      id: 0,
      width: 20,
      height: 12,
      pluginName: 'Repository Activity',
      dataPluginId: undefined,
      x: 0,
      y: 24,
      settings: undefined,
    },
    {
      id: 0,
      width: 20,
      height: 12,
      pluginName: 'Time Spent',
      dataPluginId: undefined,
      x: 20,
      y: 24,
      settings: undefined,
    },
  ],
};

export default dashboard;
