import type { DataPluginLizard, DataPluginLizards } from '../../../../interfaces/dataPluginInterfaces/dataPluginLizard.ts';

export default class Lizards implements DataPluginLizards {
  public async getAll(): Promise<DataPluginLizard[]> {
    console.log('Getting Lizard mock data');

    return [
      {
        filePath: 'backend/src/main/kotlin/service/LizardService.kt',
        maxNloc: 120,
        maxCcn: 18,
        maxTokens: 850,
        maxParameters: 7,
        maxLength: 160,
        avgNloc: 45,
        avgCcn: 7,
        avgTokens: 320,
        avgParameters: 3,
        avgLength: 62,
        functionCount: 12,
        maxLizardScore: 980,
        avgLizardScore: 410,
        normalizedMaxLizardScore: 1.0,
        normalizedAvgLizardScore: 1.0,
      },
      {
        filePath: 'backend/src/main/kotlin/service/VcsService.kt',
        maxNloc: 95,
        maxCcn: 15,
        maxTokens: 720,
        maxParameters: 6,
        maxLength: 130,
        avgNloc: 38,
        avgCcn: 6,
        avgTokens: 280,
        avgParameters: 2,
        avgLength: 55,
        functionCount: 10,
        maxLizardScore: 810,
        avgLizardScore: 360,
        normalizedMaxLizardScore: 0.83,
        normalizedAvgLizardScore: 0.88,
      },
      {
        filePath: 'frontend/src/plugins/stats/lizardStats/chart/columnChart.tsx',
        maxNloc: 80,
        maxCcn: 10,
        maxTokens: 600,
        maxParameters: 4,
        maxLength: 100,
        avgNloc: 32,
        avgCcn: 4,
        avgTokens: 220,
        avgParameters: 2,
        avgLength: 48,
        functionCount: 8,
        maxLizardScore: 620,
        avgLizardScore: 280,
        normalizedMaxLizardScore: 0.63,
        normalizedAvgLizardScore: 0.68,
      },
      {
        filePath: 'backend/src/main/kotlin/service/RepositoryService.kt',
        maxNloc: 60,
        maxCcn: 8,
        maxTokens: 440,
        maxParameters: 3,
        maxLength: 85,
        avgNloc: 25,
        avgCcn: 3,
        avgTokens: 180,
        avgParameters: 1,
        avgLength: 36,
        functionCount: 7,
        maxLizardScore: 460,
        avgLizardScore: 210,
        normalizedMaxLizardScore: 0.47,
        normalizedAvgLizardScore: 0.51,
      },
      {
        filePath: 'backend/src/main/kotlin/controller/ProjectController.kt',
        maxNloc: 42,
        maxCcn: 5,
        maxTokens: 300,
        maxParameters: 2,
        maxLength: 65,
        avgNloc: 18,
        avgCcn: 2,
        avgTokens: 120,
        avgParameters: 1,
        avgLength: 28,
        functionCount: 5,
        maxLizardScore: 320,
        avgLizardScore: 145,
        normalizedMaxLizardScore: 0.33,
        normalizedAvgLizardScore: 0.35,
      },
      {
        filePath: 'backend/src/main/kotlin/service/LizardService2.kt',
        maxNloc: 120,
        maxCcn: 18,
        maxTokens: 850,
        maxParameters: 7,
        maxLength: 160,
        avgNloc: 45,
        avgCcn: 7,
        avgTokens: 320,
        avgParameters: 3,
        avgLength: 62,
        functionCount: 12,
        maxLizardScore: 10,
        avgLizardScore: 410,
        normalizedMaxLizardScore: 0.01,
        normalizedAvgLizardScore: 1.0,
      },
    ];
  }
}
